services:
    nginx:
        build: ./nginx
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ./nginx/ssl:/etc/nginx/ssl:ro
            - ./nginx/cache:/var/cache/nginx/nuxt:delegated
            - ./nginx/logs:/var/log/nginx:delegated
        links:
            - nuxt:nuxt
        ports:
            - 80:80
            - 443:443
        depends_on:
            - nuxt
        networks:
            - app-network

    nuxt:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nuxt
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - HOST=0.0.0.0
            - NODE_ENV=production
        env_file:
            - .env
        depends_on:
            - redis
        networks:
            - app-network

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        command: redis-server --requirepass wrYphOMEtRaL
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    redis-data:
